[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]
# pypy3 hangs.
# pypy has synchronization issues.
envlist = py27, py35, py36, py37, pypy
isolated_build = True

[testenv]
commands = {envpython} setup.py test
"""

